### PR TITLE
vm_ops: libvirt support

### PR DESCRIPTION
**Pull request by vivianQizhu**
Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
Hi @Dannyb48 and @wanghekai, Would you please help review it? Thanks.

**Comment by vivianQizhu** [comment]
@btjd Would you help to review it? Many thanks.

**Review by btjd — APPROVED** [review]
Sorry it took a while, that was a lot of code to get through :) this is great work that is providing a rich set of utilities.

**Review by Dannyb48 — CHANGES_REQUESTED** [review]
Any chance you can update the README.md with a quick start usage on how to use these class?

Also, I merged in wenghaki's PR so you will need to rebase and repush again

**Comment by vivianQizhu** [comment]
@Dannyb48 Rebase the code and update README. Please help re-review, many thanks.

**Review by Dannyb48 — APPROVED** [review]
LGTM

**Pull request merged**
