### PR TITLE
Construct Bridge/Adapter

### PR DESCRIPTION
**Pull request by vivianQizhu**
Just draft a construct so that we can discuss it here, it is not supposed to be merged, and will be closed when we get a conclusion.

Signed-off-by: Qianqian Zhu <qizhu@redhat.com>

### CODE REVIEW

**Comment by vivianQizhu** [comment]
@btjd @Dannyb48 Would you help check this? Thanks!

**Review by Dannyb48 — CHANGES_REQUESTED** [review]
A few points

- I would move the current `BaseVM` and `BaseVolume` classes in the core package that are acting as the bridge interface out into the root of the `vm_ops` package. Rename the classes to either `Vm` and `Volume`
- I would Copy and Paste the current `BaseVM/Volume` classes within the libvirt packages into the `core` package since they are mostly skeletons. Cleanup the `BaseVM` init function once copied over 
- I would then rename the `BaseVm/Volume` classes in the libvirt package to like `LibvirtVm/Volume`

**Comment by vivianQizhu** [comment]
@Dannyb48 Thanks, I have updated per your comment, would you help re-review it?

**Review by Dannyb48 — CHANGES_REQUESTED** [review]
I think the last comment is under `provider`, create a package called `libvrt`, and then move all the libvirt specific modules under there. That way the next person to add new provider libs, just need to create a new package and nest their modules under that new provider specific package.

**Comment by vivianQizhu** [comment]
@Dannyb48 Thanks for your comments, updated with package `provider/libvirt`. I will follow this structure if no more comments.
@wanghekai Would you please check it and update your part accordingly? Thanks.

**Review by Dannyb48 — APPROVED** [review]

**Comment by vivianQizhu** [comment]
Thanks @Dannyb48, I am closing it.

**Pull request closed without merging**
